# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# misc
umask 0022
export GIT_SSL_NO_VERIFY=true

# source metrics virtualenv if exists
export METRICS_DIR=$HOME/metrics
if [ -e "$METRICS_DIR/bin/activate" ]; then
  source $METRICS_DIR/bin/activate
fi
